import React from "react";
import { motion } from "framer-motion";
import ChevronNav from "../components/ChevronNav";
import { div } from "framer-motion/client";

export default function TestArticle10172025() {
  return (
    <div className="min-h-screen flex flex-col items-center">
    <ChevronNav prev="/work" next="/work" />
    <motion.p
        className="
          text-4xl md:text-7xl max-w-2xl text-center mx-auto font-semibold mb-1 opacity-90 p-5
          text-[#c89116]/70
          drop-shadow-[0_0_12px_#c89116]
          transition-all duration-500 ease-out
          hover:text-[#c89116]/90 hover:scale-110 hover:drop-shadow-[0_0_20px_#c89116]
        "
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 1, delay: 0.6, ease: "easeOut" }}
      >
        Test Article - The Case for Test Articles
      </motion.p>
      <p>Renner McCreath</p>
      <p>Friday, October 17th, 2025</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices, ante vitae pharetra faucibus, tortor augue commodo augue, sed ultrices erat dui vitae sem. Morbi ac pellentesque dolor. Donec consequat eget lorem eu pellentesque. Quisque lacinia ante non mi vestibulum finibus. Suspendisse id velit vitae nunc facilisis porttitor eu a erat. Nullam vel rhoncus quam. Vivamus elementum aliquam pulvinar. Nullam elementum ligula elementum mollis pretium. Nunc nisi urna, aliquet a justo eget, dictum malesuada felis. Mauris scelerisque risus eu justo pellentesque, luctus posuere felis placerat. Duis sit amet pharetra nulla. Cras sed laoreet diam. Aenean gravida mauris non scelerisque lacinia. Sed quam mi, molestie id lobortis non, sagittis vel urna. Praesent fermentum et nibh ac malesuada. Maecenas non odio eu nibh molestie mattis.</p>
      <p>Praesent bibendum sapien sem, id imperdiet est lacinia at. Ut feugiat dolor mi. Fusce ligula elit, vulputate in risus eu, cursus fringilla arcu. Aliquam blandit cursus massa, a lobortis est condimentum et. Vivamus quam leo, accumsan ac vulputate id, vulputate imperdiet metus. Etiam at sapien sapien. Nulla venenatis quam in ligula sollicitudin, vitae tempor ex varius. Etiam sed turpis efficitur, ultrices diam vel, auctor enim. Nulla quis felis eget arcu lobortis consequat eget vel augue. Integer vestibulum orci vitae tincidunt auctor. Nam euismod dictum quam, sit amet cursus turpis gravida ac. Pellentesque a egestas urna, ac vestibulum ipsum. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pretium, risus sed bibendum tristique, magna justo varius eros, nec efficitur sapien nisl cursus diam. Curabitur lorem mauris, fringilla vitae egestas eget, malesuada et ligula.</p>
      <p>Curabitur volutpat sem molestie ante vehicula, pellentesque pharetra massa cursus. Maecenas pulvinar diam felis, vel pharetra ligula convallis a. Nunc vitae arcu lectus. Aliquam pellentesque lacus quis eros sollicitudin, non tempor arcu tincidunt. Phasellus nisl ligula, feugiat sit amet sagittis non, consequat vitae massa. Donec quis semper lacus. Ut et turpis id nulla aliquam malesuada. Cras aliquet nisl ut lectus lacinia sodales.</p>
      <p>Fusce vehicula, ligula non maximus sollicitudin, urna mauris congue diam, convallis aliquam tortor nisi id sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt leo odio, non fringilla purus cursus sit amet. Quisque vulputate ante sed neque euismod tincidunt et in risus. Nullam mollis justo eget lectus porttitor, eu mollis mi viverra. In id sollicitudin augue. Vestibulum tellus arcu, sodales vitae suscipit sit amet, bibendum in metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
      <p>Phasellus suscipit egestas leo, vitae egestas purus ultrices ut. Phasellus ante ligula, euismod ac pretium non, sodales ut enim. Praesent elementum, eros vel suscipit maximus, risus elit iaculis mauris, at consectetur lorem lacus id dui. Nullam tristique vulputate mauris, nec blandit sem. Duis varius gravida nunc, quis varius leo ultrices eu. Proin blandit, nisl vel luctus faucibus, ante nulla congue eros, sit amet luctus dui lacus id lacus. Pellentesque in semper leo. Ut sagittis risus in est elementum tempus. Cras hendrerit eleifend nisi, eu efficitur velit hendrerit ut. Cras at risus mauris. Morbi maximus, risus sit amet volutpat pretium, ex orci ullamcorper leo, a cursus tellus tellus in tortor.</p>
      <p>Curabitur vel massa interdum, tristique lacus sed, gravida ligula. Donec sed dignissim elit. Suspendisse finibus ultrices elit eget efficitur. Aenean eleifend, ligula sit amet imperdiet elementum, orci erat sollicitudin magna, ut consectetur lectus est in augue. Donec sit amet auctor velit, in tempus ligula. Integer ac bibendum libero, eget blandit orci. Phasellus bibendum eu ipsum a aliquam. Nulla ut elit laoreet, varius nunc eu, aliquam lacus. Cras tempor metus ac ligula volutpat, faucibus venenatis dolor tempor.</p>
      <p>Etiam malesuada elit sodales libero congue euismod. Integer in erat ut est lobortis malesuada quis cursus enim. Morbi condimentum augue ultrices, mollis odio et, gravida turpis. Morbi placerat ex nibh, sit amet tincidunt nulla semper et. Nulla ac sem lobortis, efficitur arcu sit amet, rutrum tellus. Pellentesque tincidunt elementum justo, eu ullamcorper nisl condimentum a. Curabitur posuere laoreet velit, et aliquam diam egestas ac. Mauris massa mauris, consectetur id nulla sed, facilisis convallis nunc. Nunc dignissim mi vel consectetur ullamcorper. Integer et ex in est semper lacinia. Nulla sodales imperdiet egestas. Duis elit tellus, luctus quis nisl eget, pulvinar aliquet massa. Aliquam imperdiet et libero a molestie. Fusce eleifend massa id felis imperdiet, a ullamcorper metus iaculis. Integer posuere eget quam vitae fringilla.</p>
      <p>Nunc sollicitudin massa pellentesque mollis auctor. Phasellus fringilla sodales ex non vehicula. Nulla ut risus eget odio aliquet mattis. Nam convallis finibus ipsum, eget ornare libero fringilla eget. Nulla elementum risus vitae tincidunt ullamcorper. Vestibulum eget arcu odio. Donec a mattis tortor. Cras dui orci, porta sed vestibulum sit amet, mollis ac nibh. Nam quis scelerisque libero, ut finibus ex. Suspendisse sagittis metus hendrerit ex bibendum aliquam. Nunc ac consequat urna. Mauris sit amet tempor ex. Nunc quis est ac neque porta placerat id non augue. Vestibulum accumsan, dui sagittis egestas egestas, lorem odio placerat nisi, in accumsan erat velit ac velit. Aenean consectetur, tellus ac tempus maximus, mauris dolor pretium lacus, quis tincidunt urna nibh eu sapien.</p>
      <p>Maecenas egestas tortor risus, sed aliquet arcu auctor a. Aliquam lacinia lobortis porta. Praesent eget nisi cursus, feugiat nibh et, efficitur diam. Nullam id venenatis lacus. Quisque eget mattis justo, ut dictum ex. Vestibulum posuere et urna vitae porttitor. Morbi ultricies eget nunc sit amet gravida. Sed faucibus ligula egestas sem consequat pellentesque. Integer urna lectus, luctus ut mi eu, viverra varius orci. Cras diam mauris, hendrerit et eleifend nec, finibus at quam. Mauris quis pretium nunc.</p>
      <p>Pellentesque nec lacus risus. Phasellus auctor, lacus at volutpat congue, urna elit efficitur enim, at tempus nulla nisi vel ex. Etiam iaculis laoreet vestibulum. Donec ut mauris nec metus tincidunt dignissim sit amet sit amet nunc. Cras sem purus, convallis in elementum sed, tempor sed lacus. Nunc vel varius enim. Fusce porta molestie libero viverra eleifend. Sed lobortis diam at sem auctor, vel mollis sem ultrices. Mauris nisi dolor, dictum sodales mi sit amet, consequat volutpat mauris. Duis at lacus eu orci pretium pharetra. Praesent bibendum mauris at congue ullamcorper. In quis ex sodales, consectetur arcu ac, lobortis lectus. Quisque consectetur sapien vel ex facilisis, non vestibulum enim posuere.</p>
    </div>
  );
}